<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AvaMovieMaker.Media</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen.Abstractions" />
    <PackageReference Include="FFmpeg.AutoGen.Bindings.DynamicallyLoaded" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaMovieMaker.Core\AvaMovieMaker.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AvaMovieMaker.Media.Tests" />
  </ItemGroup>

</Project>
