<Project>
  <PropertyGroup>
    <PublicStrings Condition="'$(PublicStrings)' == ''">false</PublicStrings>
  </PropertyGroup>

  <ItemGroup Condition="$(MSBuildProjectDirectory.StartsWith('$(AmmSrcDir)'))">
    <EmbeddedResource Update="Strings.resx"
                      StronglyTypedLanguage="CSharp"
                      StronglyTypedClassName="Strings"
                      StronglyTypedNamespace="$(RootNamespace)"
                      StronglyTypedFileName="$(IntermediateOutputPath)Strings.Designer.cs"
                      PublicClass="$(PublicStrings)" />
  </ItemGroup>

</Project>
