#!/usr/bin/env python3
"""Generates src/AvaMovieMaker/Controls/GlyphPaths.cs and the app icon from a Remix Icon checkout.

Usage: remix-glyphs.py <RemixIcon repo dir>

Each icon is one 24x24 SVG path; the generated table keeps its path data, prefixed with F1 so Avalonia fills it
with the nonzero rule the SVGs are drawn for. Add an icon by adding its Remix name to ICONS and rerunning.

The app icon, APP_ICON in the app's blue gradient, is written to tools/icons/app-icon.svg and rendered with
rsvg-convert to tools/icons/icon-512.png, which the Linux, macOS and Windows packages use. Run
tools/windows/make-icon.ps1 afterwards to rebuild the Windows .ico.
"""

import glob
import os
import re
import subprocess
import sys

ICONS = [
    "add-box-line",
    "album-line",
    "align-center",
    "align-left",
    "align-right",
    "arrow-down-s-fill",
    "arrow-go-back-line",
    "arrow-go-forward-line",
    "arrow-left-circle-line",
    "arrow-up-s-fill",
    "checkbox-indeterminate-line",
    "computer-line",
    "film-line",
    "folder-video-line",
    "layout-grid-line",
    "magic-line",
    "mail-line",
    "mic-line",
    "movie-2-fill",
    "music-2-line",
    "scissors-cut-line",
    "share-forward-box-line",
    "sparkling-fill",
    "star-fill",
    "swap-box-line",
    "task-line",
    "text",
    "video-add-line",
    "vidicon-line",
    "volume-up-line",
    "zoom-in-line",
    "zoom-out-line",
]

APP_ICON = "movie-2-fill"
APP_ICON_TOP = "#4F8EE6"
APP_ICON_BOTTOM = "#1A4AA8"


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit("usage: remix-glyphs.py <RemixIcon repo dir>")

    index = {os.path.basename(p)[:-4]: p for p in glob.glob(os.path.join(sys.argv[1], "icons", "*", "*.svg"))}
    paths = {}
    for name in ICONS:
        if name not in index:
            sys.exit(f"{name}: not in {sys.argv[1]}")
        with open(index[name], encoding="utf-8") as f:
            paths[name] = re.findall(r'<path[^>]*\sd="([^"]+)"', f.read())
    lines = [f'        ["{name}"] = "F1 {" ".join(d)}",' for name, d in paths.items()]

    here = os.path.dirname(os.path.abspath(__file__))
    svg = os.path.join(here, "app-icon.svg")
    with open(svg, "w", encoding="utf-8", newline="\n") as f:
        body = "".join(f'<path fill="url(#g)" d="{d}"/>' for d in paths[APP_ICON])
        f.write('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1">'
                f'<stop offset="0" stop-color="{APP_ICON_TOP}"/><stop offset="1" stop-color="{APP_ICON_BOTTOM}"/></linearGradient></defs>{body}</svg>\n')
    subprocess.run(["rsvg-convert", "-w", "512", "-h", "512", "-o", os.path.join(here, "icon-512.png"), svg], check=True)

    out = os.path.join(here, "..", "..", "src", "AvaMovieMaker", "Controls", "GlyphPaths.cs")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("// Generated by tools/icons/remix-glyphs.py from Remix Icon (https://remixicon.com). Do not edit by hand.\n")
        f.write("namespace AvaMovieMaker.Controls;\n\n")
        f.write("internal static class GlyphPaths\n{\n")
        f.write("    public static readonly Dictionary<string, string> Remix = new()\n    {\n")
        f.write("\n".join(lines) + "\n")
        f.write("    };\n}\n")


if __name__ == "__main__":
    main()
