namespace AvaMovieMaker.Effects.Catalog;

public enum WipeShape
{
    Horizontal = 0,
    Vertical = 1,
    Diagonal = 2,
    BarnDoorVertical = 3,
    BarnDoorHorizontal = 4,
    Box = 5,
    Diamond = 6,
    DiagonalCross = 7,
    BowTieHorizontal = 8,
    BowTieVertical = 9,
    Circle = 10,
    Circles = 11,
    Eye = 12,
    Heart = 13,
    Keyhole = 14,
    Star = 15,
    Stars = 16,
    Iris = 17,
    Inset = 18,
    FilledV = 19,
    FanIn = 20,
    FanOut = 21,
    FanUp = 22,
    SweepIn = 23,
    SweepOut = 24,
    SweepUp = 25,
    Wheel = 26,
    ZigZagHorizontal = 27,
    ZigZagVertical = 28,
    Checkerboard = 29,
}
