<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AvaMovieMaker.Interop.Mswmm</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AvaMovieMaker.Timeline\AvaMovieMaker.Timeline.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AvaMovieMaker.Interop.Mswmm.Tests" />
  </ItemGroup>

</Project>
